from fastapi import FastAPI
from fastapi.responses import PlainTextResponse
from datetime import datetime
import uvicorn

app = FastAPI(
    title="Reporting Agent AI Employee",
    description="Autonomous reporting agent that generates daily/weekly reports and anomaly alerts.",
    version="1.0.0"
)

# --- Endpoints ---
@app.get("/health")
def health_check():
    return {"status": "ok", "service": "reporting-agent"}

@app.get("/")
def root():
    return {
        "message": "Reporting Agent AI Employee is running",
        "version": "1.0.0",
        "description": "Autonomous reporting with daily/weekly summaries and anomaly detection",
        "endpoints": ["/health", "/demo/reports", "/demo/daily", "/demo/weekly", "/demo/alerts", "/docs"]
    }

@app.get("/demo/reports")
def demo_reports():
    """Demo endpoint showing all available reports."""
    return {
        "ai_analysis": "Reporting Agent has generated 2 reports and detected 2 anomalies",
        "available_reports": [
            {"type": "daily", "date": "2026-02-16", "url": "/demo/daily", "format": ["json", "markdown"]},
            {"type": "weekly", "date": "2026-02-10 to 2026-02-16", "url": "/demo/weekly", "format": ["json", "markdown"]},
        ],
        "alerts": [
            {"severity": "high", "message": "1 task overdue: 'Setup CI/CD pipeline' - 2 days late", "action": "Reassign immediately"},
            {"severity": "medium", "message": "Workflow success rate dropped to 85% this week", "action": "Review failed workflow logs"},
        ],
        "next_report_at": "2026-02-17T09:00:00",
        "generated_at": datetime.now().isoformat()
    }

@app.get("/demo/daily")
def demo_daily_report():
    """Demo daily report in JSON format."""
    return {
        "report_type": "daily",
        "date": "2026-02-16",
        "generated_by": "Reporting Agent AI Employee",
        "task_summary": {
            "total": 6,
            "completed": 1,
            "in_progress": 2,
            "pending": 2,
            "overdue": 1,
            "completion_rate_percent": 16.7
        },
        "workflow_summary": {
            "total_executions": 3,
            "successful": 2,
            "in_progress": 1,
            "failed": 0,
            "success_rate_percent": 100.0
        },
        "anomalies_detected": [
            {"type": "overdue_task", "severity": "high", "detail": "'Setup CI/CD pipeline' is 2 days overdue"},
        ],
        "ai_insights": [
            "Team velocity is on track with 2 tasks in progress",
            "1 overdue task requires immediate attention",
            "Workflow automation is performing at 100% success rate today"
        ],
        "generated_at": datetime.now().isoformat()
    }

@app.get("/demo/weekly")
def demo_weekly_report():
    """Demo weekly report in JSON format."""
    return {
        "report_type": "weekly",
        "period": "2026-02-10 to 2026-02-16",
        "generated_by": "Reporting Agent AI Employee",
        "task_summary": {
            "total_tasks": 6,
            "completed_this_week": 1,
            "new_tasks_added": 3,
            "overdue_tasks": 1,
            "avg_completion_days": 5.2,
            "top_assignee": "Alice (2 tasks)"
        },
        "workflow_summary": {
            "total_workflows_run": 8,
            "successful": 7,
            "failed": 1,
            "avg_duration_seconds": 180,
            "most_run_workflow": "Daily Data Backup (7 runs)"
        },
        "anomalies_detected": [
            {"type": "overdue_task", "severity": "high", "detail": "1 task overdue by 2+ days"},
            {"type": "workflow_failure", "severity": "medium", "detail": "1 workflow failed during the week"}
        ],
        "ai_insights": [
            "Weekly completion rate of 16.7% is below the 50% target - attention needed",
            "Workflow automation saved approximately 4.2 hours of manual work this week",
            "Recommend daily standups to improve task throughput"
        ],
        "recommendations": [
            "Reassign overdue tasks to available team members",
            "Review failed workflow root cause and fix",
            "Add 2 more tasks to in-progress to improve velocity"
        ],
        "generated_at": datetime.now().isoformat()
    }

@app.get("/demo/daily/markdown", response_class=PlainTextResponse)
def demo_daily_markdown():
    """Demo daily report in Markdown format."""
    report = f"""# Daily Report - 2026-02-16
*Generated by Reporting Agent AI Employee*

## 📋 Task Summary
| Metric | Value |
|--------|-------|
| Total Tasks | 6 |
| Completed | 1 |
| In Progress | 2 |
| Pending | 2 |
| Overdue | 1 |
| Completion Rate | 16.7% |

## ⚙️ Workflow Summary
| Metric | Value |
|--------|-------|
| Total Executions | 3 |
| Successful | 2 |
| In Progress | 1 |
| Failed | 0 |
| Success Rate | 100% |

## 🚨 Anomalies Detected
- **HIGH**: 'Setup CI/CD pipeline' is 2 days overdue — assigned to Alice

## 💡 AI Insights
- Team velocity is on track with 2 tasks in progress
- 1 overdue task requires immediate attention
- Workflow automation is performing at 100% success rate today

---
*Generated at: {datetime.now().isoformat()}*
"""
    return report

@app.get("/demo/alerts")
def demo_alerts():
    """Demo anomaly alerts detected by the Reporting Agent."""
    return {
        "alerts": [
            {
                "id": "alert-001",
                "severity": "high",
                "type": "overdue_task",
                "message": "Task 'Setup CI/CD pipeline' is overdue by 2 days",
                "affected": "Alice",
                "suggested_action": "Reassign or escalate immediately",
                "detected_at": "2026-02-16T09:00:00"
            },
            {
                "id": "alert-002",
                "severity": "medium",
                "type": "low_completion_rate",
                "message": "Weekly completion rate is 16.7%, below the 50% target",
                "affected": "Entire team",
                "suggested_action": "Schedule team review meeting",
                "detected_at": "2026-02-16T09:00:00"
            }
        ],
        "total_alerts": 2,
        "high_severity": 1,
        "medium_severity": 1,
        "generated_at": datetime.now().isoformat()
    }

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8080)

